spring:
  application:
    name: UberProject-LocationService

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  location:
    search-radius-km: 5.0
    driver-freshness-seconds: 120
